language: python
cache: pip

# Environment changes have to be manually synced with 'tox.ini'.
# See: https://github.com/travis-ci/travis-ci/issues/3024
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - "pypy"

install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile

script:
  - pipenv run tox

after_success:
  - pipenv run coveralls
